name = "GAP_Registry"
uuid = "77a0fa8e-e3a3-4df6-a7b4-afeaa12e2d26"
repo = "https://github.com/oscar-system/GAP_Registry"

[packages]
b385582e-9628-4fed-8f60-9a4f3165a09f = { name = "GAP_pkg_io", path = "G/GAP_pkg_io" }
